name: tau_platform_interface
version: 0.0.1-alpha-3
description: The Dart interface to Tau Sound.
#author: larpoux<larpoux@canardoux.xyz>
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
homepage: https://github.com/Canardoux/tau10
environment:
    sdk: '>=2.12.0 <3.0.0'
    flutter: ">=1.12.0"


dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  plugin_platform_interface: ^2.0.0
  logger: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  pedantic: ^1.11.0

